repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ['--profile', 'black']
# -   repo: git@github.com:LexisNexis-RBA/dsbsvc-crd-mbt-clear-notebook.git
#     rev: 0.2.3
#     hooks:
#     -   id: clear-notebook
#         args: [--clear, --allow-skip]
